from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ai_hq.delivery.repository_workspace import (
    CandidateSnapshot,
    TestEvidence,
)


@dataclass(frozen=True)
class VerifiedCandidate:
    """Candidate identity and evidence generated by trusted AI HQ code."""

    mission_id: str
    change_ref: str
    summary: str
    changed_files: list[str]
    evidence: dict[str, Any]


class CandidateVerifier:
    """Bind a Developer proposal to machine-observed repository state."""

    def verify(
        self,
        *,
        mission_id: str,
        proposal: Mapping[str, Any],
        snapshot: CandidateSnapshot,
        test_evidence: TestEvidence,
    ) -> VerifiedCandidate:
        if not isinstance(proposal, Mapping):
            raise TypeError("proposal must be a mapping")

        if not isinstance(mission_id, str) or not mission_id.strip():
            raise ValueError("mission_id is required")

        summary = proposal.get("summary")
        if not isinstance(summary, str) or not summary.strip():
            raise ValueError("proposal summary is required")
        summary = summary.strip()

        if not test_evidence.passed or test_evidence.exit_code != 0:
            raise ValueError(
                "workspace tests must pass before candidate verification"
            )

        identity_payload = snapshot.identity_payload(
            mission_id=mission_id.strip()
        )
        canonical = json.dumps(
            identity_payload,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")
        digest = hashlib.sha256(canonical).hexdigest()
        change_ref = f"sha256:{digest}"

        evidence = {
            "verification": "candidate_identity_verified",
            "algorithm": "sha256",
            "change_ref": change_ref,
            "workspace_id": snapshot.workspace_id,
            "repository": snapshot.repository,
            "base_ref": snapshot.base_ref,
            "diff_digest": snapshot.diff_digest,
            "content_digest": snapshot.content_digest,
            "tests": {
                "passed": test_evidence.passed,
                "exit_code": test_evidence.exit_code,
                "summary": test_evidence.summary,
                "evidence_digest": test_evidence.evidence_digest,
            },
        }

        return VerifiedCandidate(
            mission_id=mission_id.strip(),
            change_ref=change_ref,
            summary=summary,
            changed_files=list(snapshot.changed_files),
            evidence=evidence,
        )
