from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Any, Mapping


@dataclass(frozen=True)
class VerifiedCandidate:
    """
    Candidate whose identity was generated by AI HQ rather than trusted
    from model output.

    This proves deterministic candidate identity only. It does not claim
    that files were modified or tests were executed.
    """

    mission_id: str
    change_ref: str
    summary: str
    changed_files: list[str]
    evidence: dict[str, Any]


class CandidateVerifier:
    """
    Establish a deterministic immutable identity for a Developer proposal.

    Model-provided change references and evidence are deliberately excluded
    from the trusted identity/evidence boundary.
    """

    def verify(
        self,
        *,
        mission_id: str,
        proposal: Mapping[str, Any],
    ) -> VerifiedCandidate:
        if not isinstance(proposal, Mapping):
            raise ValueError(
                "proposal must be a mapping"
            )

        if (
            not isinstance(mission_id, str)
            or not mission_id.strip()
        ):
            raise ValueError(
                "mission_id is required"
            )

        summary = proposal.get("summary")

        if (
            not isinstance(summary, str)
            or not summary.strip()
        ):
            raise ValueError(
                "proposal summary is required"
            )

        summary = summary.strip()

        changed_files = proposal.get(
            "changed_files",
            [],
        )

        if not isinstance(changed_files, list):
            raise ValueError(
                "proposal changed_files must be a list"
            )

        if not all(
            isinstance(path, str)
            and bool(path.strip())
            for path in changed_files
        ):
            raise ValueError(
                "proposal changed_files must contain "
                "non-empty strings"
            )

        normalized_files = [
            path.strip()
            for path in changed_files
        ]

        identity_payload = {
            "mission_id": mission_id.strip(),
            "summary": summary,
            "changed_files": normalized_files,
        }

        canonical = json.dumps(
            identity_payload,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")

        digest = hashlib.sha256(
            canonical
        ).hexdigest()

        change_ref = f"sha256:{digest}"

        evidence = {
            "verification": (
                "candidate_identity_verified"
            ),
            "algorithm": "sha256",
            "change_ref": change_ref,
        }

        return VerifiedCandidate(
            mission_id=mission_id.strip(),
            change_ref=change_ref,
            summary=summary,
            changed_files=normalized_files,
            evidence=evidence,
        )
