from __future__ import annotations

import json
import re
from collections.abc import Callable
from typing import Any

from ai_hq.chat.model_client import ChatModelClient
from ai_hq.delivery.models import QAResult


_DEVELOPER_SYSTEM_PROMPT = """
You are the AI HQ Developer agent.

Produce a proposed repository implementation for the supplied mission as typed
whole-file changes. You are a planning and reasoning boundary only. You do not
have deployment, production, shell, host-helper, service-management, Docker,
infrastructure, git push, or git merge authority. You may not return commands,
argv, shell instructions, executable paths, environment overrides, deployment
instructions, push instructions, or merge instructions.

Return ONLY a valid JSON object with exactly these fields:

{
  "summary": "concise implementation summary",
  "changes": [
    {
      "path": "src/example.py",
      "operation": "write",
      "content": "complete UTF-8 text file contents"
    },
    {
      "path": "src/obsolete.py",
      "operation": "delete",
      "content": null
    }
  ]
}

Requirements:
- summary is required and must be non-empty.
- changes is required and must be a JSON array.
- every change must contain exactly path, operation, and content.
- path must be a non-empty repository-relative path. Runtime containment and
  symlink checks are enforced independently by the repository sandbox.
- operation must be exactly "write" or "delete".
- write requires string content containing the complete intended file.
- delete requires content to be JSON null.
- repository_context.writable_paths is the complete machine-approved list of
  files that you may write or delete. Never return a change for any other path.
- For visual, layout, spacing, sizing, colour, typography, responsive, toolbar,
  menu, or other presentation-only requests, prefer an appropriate CSS file
  from writable_paths instead of rewriting HTML, JavaScript, or templates when
  CSS alone can satisfy the request.
- Make the smallest practical change and preserve unrelated file content.
- If no suitable file exists in writable_paths, return an empty changes array
  with a concise summary explaining that no safe writable file was available.
- Do not return change_ref, test evidence, changed_files, command, argv, shell,
  executable, deployment, push, or merge controls. Candidate identity, changed
  files, and test evidence are machine-generated by AI HQ.
- Do not include Markdown fences.
- Do not include prose outside the JSON object.
""".strip()


_DEVELOPER_RETRY_INSTRUCTION = (
    "Your previous response could not be parsed as the required JSON object. "
    "Return ONLY the valid JSON object with exactly the fields \"summary\" and "
    "\"changes\" as specified in the system instructions. Do not include "
    "Markdown fences, prose, or any other content."
)


_QA_SYSTEM_PROMPT = """
You are the AI HQ QA agent.

Independently review the exact Developer candidate supplied to you.

You are a review boundary only. You do not have deployment, production,
shell, host-helper, service-management, Docker, or infrastructure authority.

The Developer change_ref is immutable. Review only that exact reference.

developer_evidence.candidate_diff is the machine-derived unified diff produced
by the trusted isolated repository sandbox. You must inspect that actual diff,
not merely the Developer summary or filenames. The associated diff/content
digests and test evidence bind the review to the verified candidate. If changed
files are present but a machine-derived candidate_diff is unavailable, the
candidate must not be approved.

Return ONLY a valid JSON object with exactly these fields:

{
  "result": "PASSED or FAILED",
  "evidence": {
    "key": "QA review evidence"
  }
}

Requirements:
- result must be exactly PASSED or FAILED.
- evidence is required and must be a non-empty JSON object.
- Do not invent or replace the Developer change_ref.
- Do not include Markdown fences.
- Do not include prose outside the JSON object.
""".strip()


_DEVELOPER_FORBIDDEN_FIELDS = frozenset(
    {
        "command",
        "argv",
        "shell",
        "executable",
        "environment",
        "cwd",
        "deploy",
        "deployment",
        "push",
        "merge",
    }
)
_CHANGE_FIELDS = frozenset({"path", "operation", "content"})


def _parse_json_object(
    raw: str,
    *,
    source: str,
) -> dict[str, Any]:
    if not isinstance(raw, str):
        raise ValueError(f"{source} must return JSON text")

    try:
        parsed = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        raise ValueError(f"{source} must return valid JSON") from None

    if not isinstance(parsed, dict):
        raise ValueError(f"{source} JSON must be an object")

    return parsed


_JSON_FENCED_PATTERN = re.compile(
    r"\s*```(?:json)?[ \t]*\r?\n(?P<body>.*?)\r?\n?[ \t]*```\s*",
    re.DOTALL,
)


def _parse_json_envelope(raw: str, *, source: str) -> dict[str, Any]:
    """Parse the required JSON object, tolerating one Markdown fence.

    Bare JSON is accepted directly. A response wrapped in exactly one JSON
    Markdown fence is also accepted, because models fence JSON in practice
    despite instructions. Any other surrounding prose is rejected so the
    caller can trigger a controlled retry.
    """
    try:
        return _parse_json_object(raw, source=source)
    except ValueError:
        pass

    match = _JSON_FENCED_PATTERN.fullmatch(raw)
    if match is None:
        raise ValueError(f"{source} must return valid JSON") from None

    return _parse_json_object(match.group("body"), source=source)


def _validate_developer_change(raw_change: Any, *, index: int) -> dict[str, Any]:
    if not isinstance(raw_change, dict):
        raise ValueError(f"Developer change {index} must be an object")
    if set(raw_change) != _CHANGE_FIELDS:
        raise ValueError(
            f"Developer change {index} must contain exactly path, operation, and content"
        )

    path = raw_change.get("path")
    if not isinstance(path, str) or not path.strip():
        raise ValueError(f"Developer change {index} requires a path")

    operation = raw_change.get("operation")
    if operation not in {"write", "delete"}:
        raise ValueError(f"Developer change {index} has invalid operation")

    content = raw_change.get("content")
    if operation == "write" and not isinstance(content, str):
        raise ValueError(f"Developer change {index} write content must be a string")
    if operation == "delete" and content is not None:
        raise ValueError(f"Developer change {index} delete content must be null")

    return {
        "path": path.strip(),
        "operation": operation,
        "content": content,
    }


class ModelBackedDeveloperAgent:
    """
    Model-backed Developer reasoning boundary.

    The model proposes typed repository file changes only. This class does not
    execute code and grants no production or command authority.
    """

    def __init__(
        self,
        model_client: ChatModelClient,
        *,
        context_provider: Callable[[str], dict[str, Any]] | None = None,
    ) -> None:
        self.model_client = model_client
        self.context_provider = context_provider

    def execute(self, *, mission_id: str) -> dict[str, Any]:
        repository_context: dict[str, Any] = {}

        if self.context_provider is not None:
            supplied = self.context_provider(mission_id)

            if not isinstance(supplied, dict):
                raise ValueError(
                    "Developer context provider must return a mapping"
                )

            repository = supplied.get("repository")
            instruction = supplied.get("instruction")
            files = supplied.get("files")

            if repository not in {"ai-hq", "dripvid"}:
                raise ValueError(
                    "Developer context requires trusted repository"
                )

            if not isinstance(instruction, str) or not instruction.strip():
                raise ValueError(
                    "Developer context requires instruction"
                )

            if not isinstance(files, list):
                raise ValueError(
                    "Developer context files must be a list"
                )

            complete_context_paths: set[str] = set()

            sanitized_files = []

            for index, item in enumerate(files):
                if not isinstance(item, dict):
                    raise ValueError(
                        f"Developer context file {index} must be an object"
                    )

                path = item.get("path")
                content = item.get("content")
                complete = item.get("complete")

                if (
                    not isinstance(path, str)
                    or not path.strip()
                    or not isinstance(content, str)
                ):
                    raise ValueError(
                        f"Developer context file {index} is invalid"
                    )

                if complete is not True:
                    # Partial source must never be writable by a
                    # whole-file Developer change.
                    continue

                normalized_path = path.strip()

                complete_context_paths.add(
                    normalized_path
                )

                sanitized_files.append(
                    {
                        "path": normalized_path,
                        "content": content,
                        "complete": True,
                    }
                )

            repository_context = {
                "repository": repository,
                "instruction": instruction.strip(),
                "files": sanitized_files,
                "writable_paths": sorted(
                    complete_context_paths
                ),
            }

        messages = [
            {
                "role": "user",
                "content": json.dumps(
                    {
                        "mission_id": mission_id,
                        "instruction": (
                            "Produce the structured Developer repository "
                            "file changes for this mission."
                        ),
                        "repository_context": repository_context,
                    },
                    sort_keys=True,
                ),
            }
        ]

        raw = self.model_client.reply(_DEVELOPER_SYSTEM_PROMPT, messages)

        try:
            candidate = _parse_json_envelope(raw, source="Developer")
        except ValueError:
            # One controlled retry for an unparseable JSON envelope. The
            # invalid response is never echoed back into the retry prompt,
            # and every schema/path/security validator below still runs on
            # the retried response. A second invalid response fails safely.
            retry_messages = [
                *messages,
                {
                    "role": "user",
                    "content": _DEVELOPER_RETRY_INSTRUCTION,
                },
            ]

            retry_raw = self.model_client.reply(
                _DEVELOPER_SYSTEM_PROMPT,
                retry_messages,
            )

            candidate = _parse_json_envelope(retry_raw, source="Developer")

        forbidden = sorted(_DEVELOPER_FORBIDDEN_FIELDS.intersection(candidate))
        if forbidden:
            raise ValueError(
                "Developer JSON contains prohibited command authority field: "
                + forbidden[0]
            )

        summary = candidate.get("summary")
        if not isinstance(summary, str) or not summary.strip():
            raise ValueError("Developer JSON requires summary")

        changes = candidate.get("changes")
        if not isinstance(changes, list):
            raise ValueError("Developer changes must be a list")

        validated_changes = [
            _validate_developer_change(change, index=index)
            for index, change in enumerate(changes)
        ]

        if self.context_provider is not None:
            for change in validated_changes:
                if change["path"] not in complete_context_paths:
                    raise ValueError(
                        "Developer change path was not supplied "
                        "with complete trusted context: "
                        + change["path"]
                    )

        return {
            "summary": summary.strip(),
            "changes": validated_changes,
        }


class ModelBackedQAAgent:
    """
    Model-backed QA reasoning boundary.

    QA receives the exact persisted Developer candidate and can only
    return PASSED or FAILED plus review evidence.
    """

    def __init__(self, model_client: ChatModelClient) -> None:
        self.model_client = model_client

    def review(
        self,
        *,
        mission_id: str,
        change_ref: str,
        summary: str,
        changed_files: list[str],
        developer_evidence: dict[str, Any],
    ) -> dict[str, Any]:
        raw = self.model_client.reply(
            _QA_SYSTEM_PROMPT,
            [
                {
                    "role": "user",
                    "content": json.dumps(
                        {
                            "mission_id": mission_id,
                            "change_ref": change_ref,
                            "summary": summary,
                            "changed_files": list(changed_files),
                            "developer_evidence": dict(developer_evidence),
                        },
                        sort_keys=True,
                    ),
                }
            ],
        )

        review = _parse_json_object(raw, source="QA")
        raw_result = review.get("result")

        try:
            qa_result = QAResult(raw_result)
        except (TypeError, ValueError):
            raise ValueError("QA result must be PASSED or FAILED") from None

        evidence = review.get("evidence")
        if not isinstance(evidence, dict) or not evidence:
            raise ValueError("QA JSON requires evidence")

        return {
            "result": qa_result,
            "evidence": dict(evidence),
        }
